### ISSUE TITLE
Update gnoboard to use gnonative NPM package

### ISSUE THREAD

**Issue by jefft0** [gnolang/gnonative#145]
Similar to what was already done to dSocial.
Also, remove the gnoboard README as not needed.

**Comment by jefft0** [comment]
Depends on upgrading to more recent version of React Native.

**Comment by D4ryl00** [comment]
We want that Gnoboard is an example app that handles manually native files and so, that it doesn't use the gnonative Expo module.
Since https://github.com/gnolang/gnonative/pull/176, the `hello` example app uses the gnonative Expo module, and because the recommended way to create new apps (thanks to the new-app makefile rule).

So I think we can close this issue.

**Comment by jefft0** [comment]
After discussion, we will revert the hello example to be pure React Native.

**Comment by jefft0** [comment]
Update: gnonative still uses native file modifications, not gnonative npm yet. Still need changes.

**Comment by jefft0** [comment]
Now using NPM file package.
